CREATE SCHEMA ops;
CREATE SCHEMA evidence;
CREATE SCHEMA research;

CREATE TABLE ops.sources (
 id TEXT PRIMARY KEY, name TEXT NOT NULL, kind TEXT NOT NULL, url TEXT NOT NULL,
 enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)), tags TEXT NOT NULL DEFAULT '[]',
 cadence_hours DOUBLE PRECISION NOT NULL DEFAULT 24, initialized_at TIMESTAMPTZ,
 last_checked TIMESTAMPTZ, last_success TIMESTAMPTZ, error TEXT
);
CREATE TABLE ops.inbox_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_id TEXT NOT NULL REFERENCES ops.sources(id), source_kind TEXT NOT NULL,
 identity TEXT NOT NULL, title TEXT NOT NULL, url TEXT NOT NULL,
 published_at TEXT, observed_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
 summary TEXT NOT NULL, content_hash TEXT NOT NULL,
 baseline INTEGER NOT NULL DEFAULT 0 CHECK(baseline IN (0,1)),
 status TEXT NOT NULL DEFAULT 'new' CHECK(status IN ('new','shortlist','archive')),
 review_note TEXT NOT NULL DEFAULT '', reviewed_at TIMESTAMPTZ,
 UNIQUE(source_id,identity)
);
COMMENT ON COLUMN ops.inbox_items.published_at IS 'Legacy source timestamp text, possibly missing timezone; typed evidence time stored separately';
CREATE INDEX inbox_url ON ops.inbox_items(url);
CREATE INDEX inbox_status_time ON ops.inbox_items(status,updated_at DESC);
CREATE TABLE ops.item_revisions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 item_id BIGINT NOT NULL REFERENCES ops.inbox_items(id), observed_at TIMESTAMPTZ NOT NULL,
 change_kind TEXT NOT NULL, title TEXT NOT NULL, url TEXT NOT NULL, published_at TEXT,
 summary TEXT NOT NULL, content_hash TEXT NOT NULL
);
CREATE TABLE ops.review_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 item_id BIGINT NOT NULL REFERENCES ops.inbox_items(id), reviewed_at TIMESTAMPTZ NOT NULL,
 old_status TEXT NOT NULL, new_status TEXT NOT NULL, note TEXT NOT NULL
);
CREATE TABLE ops.source_fetches (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_id TEXT NOT NULL REFERENCES ops.sources(id), observed_at TIMESTAMPTZ NOT NULL,
 content_hash TEXT NOT NULL, relative_path TEXT NOT NULL, charset TEXT NOT NULL
);
CREATE TABLE ops.crawled_documents (
 url TEXT PRIMARY KEY, item_id BIGINT REFERENCES ops.inbox_items(id),
 last_attempt TIMESTAMPTZ NOT NULL, fetched_at TIMESTAMPTZ, document_path TEXT,
 provenance TEXT, status TEXT NOT NULL, error TEXT
);
CREATE TABLE ops.crawl_jobs (
 id TEXT PRIMARY KEY, status TEXT NOT NULL, started_at TIMESTAMPTZ NOT NULL,
 finished_at TIMESTAMPTZ, result_artifact TEXT
);
CREATE TABLE ops.job_events (
 id TEXT PRIMARY KEY, job_id TEXT NOT NULL REFERENCES ops.crawl_jobs(id),
 at TIMESTAMPTZ NOT NULL, url TEXT NOT NULL, status TEXT NOT NULL,
 details JSONB NOT NULL DEFAULT '{}'
);
CREATE TABLE ops.migration_runs (
 id TEXT PRIMARY KEY, started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 finished_at TIMESTAMPTZ, report JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE evidence.artifacts (
 sha256 TEXT PRIMARY KEY CHECK(sha256 ~ '^[0-9a-f]{64}$'),
 bytes BIGINT NOT NULL CHECK(bytes>=0), format TEXT NOT NULL, registered_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE evidence.artifact_locations (
 sha256 TEXT NOT NULL REFERENCES evidence.artifacts(sha256),
 path TEXT NOT NULL, PRIMARY KEY(sha256,path)
);
CREATE TABLE evidence.documents (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 canonical_url TEXT NOT NULL UNIQUE, original_url TEXT NOT NULL,
 normalization_version INTEGER NOT NULL DEFAULT 1, current_version_id BIGINT
);
CREATE TABLE evidence.document_versions (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 document_id BIGINT NOT NULL REFERENCES evidence.documents(id), content_hash TEXT NOT NULL,
 title TEXT NOT NULL, body TEXT NOT NULL, markdown TEXT NOT NULL,
 author TEXT, published_at TIMESTAMPTZ, published_at_raw TEXT,
 event_at TIMESTAMPTZ, effective_at TIMESTAMPTZ,
 provenance TEXT NOT NULL, extractor_version TEXT NOT NULL,
 metadata JSONB NOT NULL DEFAULT '{}', recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(document_id,content_hash), UNIQUE(id,document_id)
);
ALTER TABLE evidence.documents ADD CONSTRAINT current_document_version
 FOREIGN KEY(current_version_id,id) REFERENCES evidence.document_versions(id,document_id);
CREATE TABLE evidence.observations (
 id TEXT PRIMARY KEY, document_id BIGINT REFERENCES evidence.documents(id),
 version_id BIGINT REFERENCES evidence.document_versions(id), source_id TEXT REFERENCES ops.sources(id),
 attempted_at TIMESTAMPTZ, observed_at TIMESTAMPTZ, status TEXT NOT NULL,
 raw_artifact TEXT REFERENCES evidence.artifacts(sha256),
 document_artifact TEXT REFERENCES evidence.artifacts(sha256),
 metadata JSONB NOT NULL DEFAULT '{}', recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 FOREIGN KEY(version_id,document_id) REFERENCES evidence.document_versions(id,document_id)
);
CREATE INDEX observation_time ON evidence.observations(document_id,observed_at DESC);
CREATE TABLE evidence.inbox_document_links (
 item_id BIGINT NOT NULL REFERENCES ops.inbox_items(id),
 document_id BIGINT NOT NULL REFERENCES evidence.documents(id), PRIMARY KEY(item_id,document_id)
);

CREATE TABLE research.records (
 id TEXT PRIMARY KEY, kind TEXT NOT NULL CHECK(kind IN ('case','hypothesis')),
 title TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', current_version_id BIGINT
);
CREATE TABLE research.record_versions (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 record_id TEXT NOT NULL REFERENCES research.records(id), body TEXT NOT NULL,
 content_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 metadata JSONB NOT NULL DEFAULT '{}', UNIQUE(record_id,content_hash), UNIQUE(id,record_id)
);
ALTER TABLE research.records ADD CONSTRAINT current_research_version
 FOREIGN KEY(current_version_id,id) REFERENCES research.record_versions(id,record_id);
CREATE TABLE research.evidence_links (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 record_version_id BIGINT NOT NULL REFERENCES research.record_versions(id),
 document_version_id BIGINT REFERENCES evidence.document_versions(id),
 unresolved_url TEXT, relation TEXT NOT NULL CHECK(relation IN ('supports','refutes','background')),
 CHECK((document_version_id IS NOT NULL) <> (unresolved_url IS NOT NULL)),
 UNIQUE NULLS NOT DISTINCT(record_version_id,document_version_id,unresolved_url,relation)
);
CREATE TABLE research.datasets (
 id TEXT PRIMARY KEY, kind TEXT NOT NULL, artifact TEXT NOT NULL REFERENCES evidence.artifacts(sha256),
 synthetic BOOLEAN NOT NULL DEFAULT false, metadata JSONB NOT NULL DEFAULT '{}'
);
CREATE TABLE research.experiment_runs (
 id TEXT PRIMARY KEY, dataset_id TEXT REFERENCES research.datasets(id),
 result_artifact TEXT REFERENCES evidence.artifacts(sha256), code_artifact TEXT REFERENCES evidence.artifacts(sha256),
 code_revision TEXT, ran_at TIMESTAMPTZ, metadata JSONB NOT NULL DEFAULT '{}'
);
CREATE FUNCTION evidence.prevent_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Historical rows are immutable; append a new version'; END $$;
CREATE TRIGGER immutable_document_version BEFORE UPDATE OR DELETE ON evidence.document_versions
 FOR EACH ROW EXECUTE FUNCTION evidence.prevent_mutation();
CREATE TRIGGER immutable_observation BEFORE UPDATE OR DELETE ON evidence.observations
 FOR EACH ROW EXECUTE FUNCTION evidence.prevent_mutation();
CREATE TRIGGER immutable_record_version BEFORE UPDATE OR DELETE ON research.record_versions
 FOR EACH ROW EXECUTE FUNCTION evidence.prevent_mutation();
CREATE TRIGGER immutable_review BEFORE UPDATE OR DELETE ON ops.review_events
 FOR EACH ROW EXECUTE FUNCTION evidence.prevent_mutation();
CREATE TRIGGER immutable_item_revision BEFORE UPDATE OR DELETE ON ops.item_revisions
 FOR EACH ROW EXECUTE FUNCTION evidence.prevent_mutation();
